# Generated by Django 4.2 on 2023-08-25 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=100)),
                ('date_livraison', models.DateField(default=django.utils.timezone.now)),
                ('date_commande', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('commande', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='commandefournisseur.commandefournisseur')),
                ('produit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
        ),
    ]
